CREATE TABLE "vehiclesTable" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"make" varchar(255) NOT NULL,
	"model" varchar(255) NOT NULL,
	"year" integer NOT NULL,
	"vin" varchar(50) NOT NULL,
	"engineNumber" varchar(50) NOT NULL,
	"licensePlate" varchar(20) NOT NULL,
	"fuelType" varchar(100) NOT NULL,
	"transmission" varchar(50) NOT NULL,
	"currentMileage" integer NOT NULL,
	"colour" varchar(50) NOT NULL,
	"imageUrl" varchar(500),
	"vehicleType" varchar(50) NOT NULL,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"lastInspectionDate" varchar(50),
	CONSTRAINT "vehiclesTable_vin_unique" UNIQUE("vin"),
	CONSTRAINT "vehiclesTable_licensePlate_unique" UNIQUE("licensePlate")
);
--> statement-breakpoint
CREATE TABLE "inspectionTable" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"date" timestamp DEFAULT now() NOT NULL,
	"mileage" integer NOT NULL,
	"overall_condition" varchar(100) NOT NULL,
	"exterior_windshield" varchar(50),
	"exterior_mirrors" varchar(50),
	"exterior_lights" varchar(50),
	"exterior_tires" varchar(50),
	"engine_oil" varchar(50),
	"engine_coolant" varchar(50),
	"engine_brake_fluid" varchar(50),
	"engine_transmission_fluid" varchar(50),
	"engine_power_steering" varchar(50),
	"engine_battery" varchar(50),
	"interior_seats" varchar(50),
	"interior_seatbelts" varchar(50),
	"interior_horn" varchar(50),
	"interior_ac" varchar(50),
	"windows" varchar(50),
	"brakes" varchar(50),
	"exhaust" varchar(50),
	"lights_indicators" varchar(50),
	"spare_tire" varchar(50),
	"jack" varchar(50),
	"wheel_spanner" varchar(50),
	"wheel_lock_nut_tool" varchar(50),
	"fire_extinguisher" varchar(50),
	"notes" text,
	"faults_images_url" text[],
	"odometer_image_url" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "maintenance_historyTable" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"date" timestamp DEFAULT now(),
	"mileage" integer NOT NULL,
	"odometer_image_url" varchar(255),
	"maintenance_type" varchar(100) NOT NULL,
	"description" text,
	"performed_by" varchar(50) NOT NULL,
	"service_center" varchar(255),
	"cost" integer,
	"parts" text[],
	"invoices_url" text[],
	"photos_url" text[],
	"next_service_date" timestamp,
	"next_service_mileage" integer
);
