CREATE TABLE "inspectionTable" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"date" timestamp DEFAULT now() NOT NULL,
	"mileage" integer NOT NULL,
	"overall_condition" varchar(100) NOT NULL,
	"exterior_windshield" varchar(50),
	"exterior_mirrors" varchar(50),
	"exterior_lights" varchar(50),
	"exterior_tires" varchar(50),
	"engine_oil" varchar(50),
	"engine_coolant" varchar(50),
	"engine_brake_fluid" varchar(50),
	"engine_transmission_fluid" varchar(50),
	"engine_power_steering" varchar(50),
	"engine_battery" varchar(50),
	"interior_seats" varchar(50),
	"interior_seatbelts" varchar(50),
	"interior_horn" varchar(50),
	"interior_ac" varchar(50),
	"windows" varchar(50),
	"brakes" varchar(50),
	"exhaust" varchar(50),
	"lights_indicators" varchar(50),
	"spare_tire" varchar(50),
	"jack" varchar(50),
	"wheel_spanner" varchar(50),
	"wheel_lock_nut_tool" varchar(50),
	"fire_extinguisher" varchar(50),
	"notes" text,
	"faults_images_url" text[],
	"odometer_image_url" varchar(255)
);
