name: EAS Android Development Build

on:
  push:
    branches:
      - main   # triggers on all branches
  pull_request:
    branches:
      - main  # triggers on pull requests to the main branch

jobs:
  build-android-development:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: moovSafe-mobile  # run commands inside your app folder

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install project dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 5️⃣ Configure EAS CLI
      - name: Build  Android Development Build APK
        run:  eas build --platform android --profile development --non-interactive
      