name: MoovSafe Mobile CI

on:
  push:
    branches:
      - main
    paths:
      - "moovSafe-mobile/**"
  pull_request:
    branches:
      - main
    paths:
      - "moovSafe-mobile/**"

jobs:
  expo-build:
    runs-on: ubuntu-latest
    env:
      EAS_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: moovSafe-mobile/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('moovSafe-mobile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: ./moovSafe-mobile
        run: npm install

      # Step 5: Install EAS CLI globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 6: Prebuild Expo project (checks for errors)
      - name: Prebuild Expo project
        working-directory: ./moovSafe-mobile
        run: eas prebuild --non-interactive

  