name: Backend API CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - "!api/README.md"
      - "!api/*.md"
      - "!api/.gitignore"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - "!api/README.md"
      - "!api/*.md"
      - "!api/.gitignore"

jobs:
  # Quality checks and testing
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        working-directory: ./api
        run: pnpm install

      - name: Run unit tests
        working-directory: ./api
        run: pnpm test:ci

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        if: success()
        with:
          directory: ./api/coverage
          flags: api
        continue-on-error: true

      - name: Type check
        working-directory: ./api
        run: npx tsc --noEmit

      - name: Lint check
        working-directory: ./api
        run: pnpm run lint || echo "No lint script available"
        continue-on-error: true

      - name: Build backend
        working-directory: ./api
        run: npm run build
        env:
          CI: false

  # Deploy to staging/development environment
  deploy-staging:
    needs: quality-check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Genezio
        uses: Genez-io/genezio-github-action@v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}

      - name: Install backend dependencies
        working-directory: ./api
        run: npm install

      - name: Build backend
        working-directory: ./api
        run: npm run build
        env:
          CI: false

      - name: Deploy to staging
        working-directory: ./api
        run: genezio deploy --stage staging || genezio deploy
        env:
          CI: false

  # Deploy to production
  deploy-production:
    needs: quality-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Genezio
        uses: Genez-io/genezio-github-action@v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}

      - name: Install backend dependencies
        working-directory: ./api
        run: npm install

      - name: Build backend
        working-directory: ./api
        run: npm run build
        env:
          CI: false

      - name: Deploy to production
        working-directory: ./api
        run: genezio deploy --stage production || genezio deploy
        env:
          CI: false
